### ISSUE TITLE
Remove hardcoded cassandra version from tests and other files

### ISSUE THREAD

**Issue by porridge** [mesosphere/kudo-cassandra-operator#136]
The versions in [`nodetool.go`](https://github.com/mesosphere/kudo-cassandra-operator/blob/7f000369d3e718e57660567ae78f53ed2970b93b/tests/cassandra/nodetool.go#L142), [`00-install.yaml`](https://github.com/mesosphere/kudo-cassandra-operator/blob/26724f0addec27dd1302ca7a194b21cb7990431c/kuttl-tests/suites/common/install-test/00-install.yaml#L5) and [benchmarks](https://github.com/mesosphere/kudo-cassandra-operator/blob/26724f0addec27dd1302ca7a194b21cb7990431c/benchmarks/kassandra_stress_replica_set.yaml.template#L24) should all be parameterized.

**Comment by rishabh96b** [comment]
This has been fixed.
